### ISSUE TITLE
Not compiling 

### ISSUE THREAD

**Issue by MiluchOK** [ssteveli/hookbin#7]
I tried compiling the project ,but got error: 

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project hookbin: Compilation failure: Compilation failure: 
[ERROR] /Users/amilyukov/projects/hookbin/src/main/java/hookbin/spring/web/api/BucketController.java:[201,6] cannot find symbol
[ERROR]   symbol:   class Data
[ERROR]   location: class hookbin.spring.web.api.BucketController
[ERROR] /Users/amilyukov/projects/hookbin/src/main/java/hookbin/spring/web/api/BucketController.java:[202,6] cannot find symbol
[ERROR]   symbol:   class Builder
[ERROR]   location: class hookbin.spring.web.api.BucketController
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

Are there special instructions to compile the code?

**Comment by ssteveli** [comment]
Looks like a lombok issue, it's a dependency: https://projectlombok.org.
